#!/bin/bash

echo "=== Push to GitHub Script ==="
echo ""
echo "Repository: https://github.com/rcz87/News1.git"
echo "Branch: main"
echo "Status: Ready to push 3 commits"
echo ""
echo "To push manually, run one of these commands:"
echo ""
echo "Option 1 - With GitHub Token:"
echo "git push https://YOUR_GITHUB_TOKEN@github.com/rcz87/News1.git main"
echo ""
echo "Option 2 - With SSH (if SSH key is configured):"
echo "git remote set-url origin git@github.com:rcz87/News1.git"
echo "git push origin main"
echo ""
echo "Option 3 - Interactive push:"
echo "git push origin main"
echo "(you'll be prompted for username/password)"
echo ""
echo "Current commits to push:"
git log --oneline origin/main..HEAD
echo ""
echo "=== End of Script ==="
